
nc: 1  # number of classes
backbone:
  - [-1, 1, Timm, [512, 'efficientnet_b5', True, True, 0, True]]  # Layer 0: returns list of block outputs
  - [0, 1, Index, [64, 2]]     # Layer 1: P3 = Block 2 output (32x32)
  - [0, 1, Index, [176, 4]]    # Layer 2: P4 = Block 4 output (16x16)
  - [0, 1, Index, [512, 6]]    # Layer 3: P5 = Block 6 output (8x8)
  - [-1, 1, SPPF, [512, 5]]    # Layer 4: SPPF on P5 (8x8) to enhance receptive field

head:
  # 上采样/拼接/检测头，通道数建议与 backbone 输出保持一致
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]            # 5, SPPF上采样 (8->16)
  - [[-1, 2], 1, Concat, [1]]                             # 6, 拼接16x16的两个特征
  - [-1, 3, C2f, [176]]                                   # 7, 通道数和P4对齐

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]            # 8, 上采样 (16->32)
  - [[-1, 1], 1, Concat, [1]]                             # 9, 拼接32x32的两个特征
  - [-1, 3, C2f, [64]]                                    # 10, 通道数和P3对齐

  - [-1, 1, Conv, [64, 3, 2]]                             # 11, 下采样 (32->16)
  - [[-1, 7], 1, Concat, [1]]                             # 12, 拼接16x16的两个特征
  - [-1, 3, C2f, [176]]                                   # 13

  - [-1, 1, Conv, [176, 3, 2]]                            # 14, 下采样 (16->8)
  - [[-1, 4], 1, Concat, [1]]                             # 15, 拼接8x8的两个特征
  - [-1, 3, C2f, [512]]                                   # 16

  - [[10, 13, 16], 1, Detect, [nc]]                       # 17, 检测头, 多尺度
